# Generated by Django 4.2.16 on 2024-09-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='area',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
